Ini apa ya yang salah kenapa selalu keluar exception di bawah ini pas mau insert staf baru...
Cause: Class name is wrong or classpath is not set for : com.mysql.jdbc.jdbc2.optional.MysqlDataSource
java.lang.IllegalArgumentException: Unknown entity bean class: class AvatarEntity.Staff, please verify that this class has been marked with the @Entity annotation.